version: '3.7'

services:
  caddy:
    image: ${DOCKER_REGISTRY_PREFIX}caddy:2
    volumes:
      - caddy-data:/data/caddy
    command: caddy reverse-proxy --from ${EXTERNAL_URL:-localhost} --to firezone:13000
    ports:
      - 80:80
      - 443:443

  firezone:
    image: ${DOCKER_REGISTRY_PREFIX}firezone/firezone
    ports:
      - 51820:51820/udp
    volumes:
      - firezone-data:/var/firezone
    env_file:
      # This should contain a list of env vars for configuring Firezone.
      # See https://docs.firezone.dev/reference/env-vars for more info.
      - ${FZ_INSTALL_DIR:-.}/.env
    cap_add:
      # Needed for WireGuard and firewall support.
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      # Needed for masquerading and NAT.
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv4.ip_forward=1
      - net.ipv6.conf.all.forwarding=1
    depends_on:
      - postgres

  postgres:
    image: ${DOCKER_REGISTRY_PREFIX}postgres:15
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DATABASE_NAME:-firezone}
      POSTGRES_USER: ${DATABASE_USER:-postgres}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:?err}

# Postgres needs a named volume to prevent perms issues on non-linux platforms
volumes:
  postgres-data:
  caddy-data:
  firezone-data:
